### ISSUE TITLE
Include example on how to include in basic shiny app [Documentation request]

### ISSUE THREAD

**Issue by kyleweise** [mrjoh3/cytoscape#1]
I think an example on how to use this HTMLWidget for a R/Shiny app would useful to newer users. Similar to [here](https://github.com/cytoscape/r-cytoscape.js/tree/master/inst/examples/shiny) (although I like this implementation more, the use of `%>%` makes it feel more R-like).

**Comment by mrjoh3** [comment]
to run the example see the readme file section [here](https://github.com/mrjoh3/cytoscape#shiny-example)
